### ISSUE TITLE
Falha ao acessar o ponto principal

### ISSUE THREAD

**Issue by ktfth** [desenvolvimento-web/crud-php#1]
[Sat May  9 20:11:01 2020] PHP Warning:  require_once(/home/ktfth/war/crud-php/public/../vendor/autoload.php): failed to open stream: No such file or directory in /home/ktfth/war/crud-php/public/index.php on line 3
[Sat May  9 20:11:01 2020] PHP Fatal error:  require_once(): Failed opening required '/home/ktfth/war/crud-php/public/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/ktfth/war/crud-php/public/index.php on line 3
[Sat May  9 20:11:01 2020] 127.0.0.1:48612 [500]: / - require_once(): Failed opening required '/home/ktfth/war/crud-php/public/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/ktfth/war/crud-php/public/index.php on line 3

**Comment by messiasdias** [comment]
Ktfth, Já rodou o comando "composer dump-autoload" ?
